version: '3'
services:
  agentes-web:
    container_name: agentes-web
    build:
        context: .
    ports: 
      - 3003:3000
    depends_on:
      - agentes-mongo
    networks:
      - martell
    restart: unless-stopped
  agentes-mongo:
    image: mongo:5.0.25
    container_name: agentes-mongo
    volumes:
      - data:/data/db
    ports:
      - 27018:27017
    networks:
      - martell
    restart: unless-stopped

volumes:
  data:

networks:
  martell:
    external: true
    name: martell
